### ISSUE TITLE
Breaking a Plant Jar drops nothing

### ISSUE THREAD

**Issue by calloatti** [CoolMineman/Plant-In-A-Jar#1]
plantinajar-1.1.1+1.16.1.jar

Breaking a Plant Jar drops nothing, even using silk touch.

**Comment by CoolMineman** [comment]
looks like I forgot the loot table :(

**Comment by calloatti** [comment]
Don't forget to also drop the items inside the Plant Jar (Dirt/Seed/Sapling, etc). Or not, design choice I guess.
