### ISSUE TITLE
Crash when adding Rubber trees from Tech Reborn

### ISSUE THREAD

**Issue by SnappierSoap318** [CoolMineman/Plant-In-A-Jar#16]
Server and client crashes when trying to plant rubber trees from Tech Reborn

Server Crash report:
[server-crash report.txt](https://github.com/CoolMineman/Plant-In-A-Jar/files/6554974/server-crash.report.txt)

Client Crash report: 
[crash-2021-05-27_20.28.51-client.txt](https://github.com/CoolMineman/Plant-In-A-Jar/files/6554950/crash-2021-05-27_20.28.51-client.txt)

**Comment by CoolMineman** [comment]
update to 2.1.2

**Comment by SnappierSoap318** [comment]
Still Crashing after updating the mod to 2.1.2
