### ISSUE TITLE
1.18.2 Port

### ISSUE THREAD

**Issue by TehcJS** [CoolMineman/Plant-In-A-Jar#24]
fixes #23

**Comment by PTOM76** [comment]
https://github.com/PTOM76/Plant-In-A-Jar/releases/tag/v2.2.3
I ported it to 1.18.2.
I also sent a pull request.

**Comment by greensad** [comment]
> 

Just fyi I can grow crops using your update but not trees for some reason, could be a conflict

**Comment by itsdinkd** [comment]
Yess!
