### ISSUE TITLE
1.20.1 Error with Visuality

### ISSUE THREAD

**Issue by spoorn** [CoolMineman/Plant-In-A-Jar#34]
Not sure if a Visuality or Plant-in-a-Jar problem, but removing PIAJ resolves the error:

[crash-2023-07-18_21.29.37-client.txt](https://github.com/CoolMineman/Plant-In-A-Jar/files/12091083/crash-2023-07-18_21.29.37-client.txt)

**Comment by F1rz-L** [comment]
I also got the same problem, crash on startup
