### ISSUE TITLE
Enhancement: Allow wildcards in the config

### ISSUE THREAD

**Issue by Katorone** [CoolMineman/Plant-In-A-Jar#5]
On our server we've found that adjusting the growth time to 200 is fine for crops, but slow for saplings.  I can adjust the growth times of crops individually just fine, but having wildcard support would make this process considerably easier.

Instead of adding each seed or each sapling, it would be possible to do  _*:*sapling: -100_, or _betternether:*: +100_.

**Comment by CoolMineman** [comment]
https://www.curseforge.com/minecraft/mc-mods/plant-in-a-jar/files/3026293
I've added support for Regex Growth Modifiers in 1.6.1 and it can do similar things to this see the changelog for an example.

**Comment by Katorone** [comment]
Awesome!  Thank you so much!
